image: python:3.8

stages:
  - build
  - deploy

before_script:
  - apt-get update && apt-get -y install git

build:
  stage: build
  script:
    - pip install -r requirements.txt

deploy:
  stage: deploy
  script:
    - streamlit run app.py --server.enableCORS false --server.port $PORT
