stages:
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build:
  stage: build
  image:
    name: python:3.9
    entrypoint: [""]
  cache:
    paths:
      - .cache/pip
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - streamlit run app.py
