image: python:3.8

stages:
  - build
  - deploy

before_script:
  - apt-get update && apt-get -y install git

build:
  stage: build
  script:
    - pip install -r requirements.txt

pages:
  stage: deploy
  script:
    - mkdir .public
    - streamlit run app.py --server.enableCORS false --server.port 8080 &
    - sleep 5
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

