stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build-job:
  stage: build
  image:
    name: python:3.9
    entrypoint: [""]
  cache:
    paths:
      - .cache/pip
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
  script:
    - echo "Building the project..."
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Compile complete."

deploy-job:
  stage: deploy
  environment: production
  image:
    name: python:3.9
    entrypoint: [""]
  cache:
    paths:
      - .cache/pip
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Deploying the project..."
    - streamlit run app.py
    - echo "Application successfully deployed."
    

